# Generated by Django 3.2.5 on 2021-08-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
    ]
